//! Autogenerated weights for `pallet_create_token`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `createfi-node`, CPU: `Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/solochain-template-node
// benchmark
// pallet
// --chain
// dev
// --steps
// 50
// --repeat
// 20
// --pallet
// pallet_create_token
// --extrinsic
// *
// --wasm-execution
// compiled
// --output
// pallets/create-token/src/weights.rs
// --template
// .maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_create_token`.
pub trait WeightInfo {
	fn mint_tokens() -> Weight;
	fn burn_tokens() -> Weight;
	fn transfer_tokens() -> Weight;
	fn stake_tokens() -> Weight;
	fn unstake_tokens() -> Weight;
	fn claim_rewards() -> Weight;
}

/// Weights for `pallet_create_token` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `CreateToken::Balances` (r:1 w:1)
	/// Proof: `CreateToken::Balances` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CreateToken::TotalSupply` (r:1 w:1)
	/// Proof: `CreateToken::TotalSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn mint_tokens() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3514`
		//  Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(20_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `CreateToken::Balances` (r:1 w:1)
	/// Proof: `CreateToken::Balances` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CreateToken::TotalSupply` (r:1 w:1)
	/// Proof: `CreateToken::TotalSupply` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn burn_tokens() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3514`
		//  Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(20_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `CreateToken::Balances` (r:2 w:2)
	/// Proof: `CreateToken::Balances` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn transfer_tokens() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `6048`
		//  Minimum execution time: 30_000_000 picoseconds.
		Weight::from_parts(30_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6048))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `CreateToken::Balances` (r:1 w:1)
	/// Proof: `CreateToken::Balances` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CreateToken::StakedBalances` (r:1 w:1)
	/// Proof: `CreateToken::StakedBalances` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CreateToken::TotalStaked` (r:1 w:1)
	/// Proof: `CreateToken::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `CreateToken::GovernancePower` (r:1 w:1)
	/// Proof: `CreateToken::GovernancePower` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CreateToken::TotalGovernancePower` (r:1 w:1)
	/// Proof: `CreateToken::TotalGovernancePower` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn stake_tokens() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `8602`
		//  Minimum execution time: 40_000_000 picoseconds.
		Weight::from_parts(40_000_000, 0)
			.saturating_add(Weight::from_parts(0, 8602))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `CreateToken::StakedBalances` (r:1 w:1)
	/// Proof: `CreateToken::StakedBalances` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CreateToken::Balances` (r:1 w:1)
	/// Proof: `CreateToken::Balances` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CreateToken::TotalStaked` (r:1 w:1)
	/// Proof: `CreateToken::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `CreateToken::GovernancePower` (r:1 w:1)
	/// Proof: `CreateToken::GovernancePower` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CreateToken::TotalGovernancePower` (r:1 w:1)
	/// Proof: `CreateToken::TotalGovernancePower` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn unstake_tokens() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `8602`
		//  Minimum execution time: 40_000_000 picoseconds.
		Weight::from_parts(40_000_000, 0)
			.saturating_add(Weight::from_parts(0, 8602))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `CreateToken::StakedBalances` (r:1 w:0)
	/// Proof: `CreateToken::StakedBalances` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CreateToken::LastRewardBlock` (r:1 w:1)
	/// Proof: `CreateToken::LastRewardBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `CreateToken::PendingRewards` (r:1 w:1)
	/// Proof: `CreateToken::PendingRewards` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CreateToken::Balances` (r:1 w:1)
	/// Proof: `CreateToken::Balances` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn claim_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `6046`
		//  Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(35_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6046))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}